# Generated by Django 5.1.5 on 2025-03-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
